### ISSUE TITLE
关于扩散过程的一些咨询

### ISSUE THREAD

**Issue by ZhangYuan1998** [hjf1997/USTD#3]
作者您好，在阅读您的代码时，我注意到对于不同的数据集，优化目标有所区别：PEMS03 的优化目标为 input，而 AirBJ 的优化目标为 noise。像 DDPM 或 DDIM 这样的扩散模型，其优化目标通常设置为 noise。想向您请教一下，选择 input 作为优化目标的设计初衷是？

个人的一点理解是：如果在训练过程中将 input 作为优化目标，那么扩散步数T的作用可能会被削弱。因为每一步的目标其实都在直接还原到输入数据本身，这使得扩散过程看起来更像是一个加噪声的一步还原过程，而不是逐步去噪的过程。而如果以 noise 作为优化目标，每一步的目标是去除当前步数对应的噪声，这更符合扩散模型逐步去噪的思想。我也试着将PEMS03的优化目标作为noise，但效果非常差，甚至无法收敛。

期待您的指正与回复！

涉及的代码：
if self.objective == 'noise':
    coeff1 = 1 / self.alpha[t] ** 0.5
    coeff2 = (1 - self.alpha[t]) / (1 - self.alpha_hat[t]) ** 0.5
    current_sample = coeff1 * (current_sample - coeff2 * prediction)
    if t > 0:
        noise = torch.randn_like(current_sample) if not deterministic else torch.zeros_like(current_sample)
        sigma = (
            (1.0 - self.alpha_hat[t - 1]) / (1.0 - self.alpha_hat[t]) * self.beta[t]
        ) ** 0.5
        current_sample += sigma * noise
elif self.objective == 'input':
    alpha_hat = self.alpha_hat[t]
    alpha_hat_prev = self.alphas_hat_prev[t]
    noise = (current_sample - alpha_hat.sqrt() * prediction) / (1 - alpha_hat).sqrt()
    current_sample = alpha_hat_prev.sqrt() * prediction + \
                     (1 - alpha_hat_prev).sqrt() * noise

**Comment by hjf1997** [comment]
Yes, you are right. When I was conducting the experiments, I found that setting noise as the reconstruction target would lead to degraded performance for certain datasets. This may be due to data distribution characteristics but I failed to figure out the concrete reasons. Then, I read some diffusion papers in different areas like CV, and found some would set the input as the target. Thus, I tried this and the results went back to normal.

**Comment by ZhangYuan1998** [comment]
Thank you very much for your response. This is indeed a difficult issue to explain. However, I’ve also noticed that some time series forecasting methods have adopted this strategy as well, and they show strong data generation capabilities. Once again, thank you for your open-source contributions and prompt response！
